function [fitresult, gof] = createFit(yy, xx, J2)
%CREATEFIT(YY,XX,J2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : yy
%      Y Input : xx
%      Z Output: J2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-May-2015 13:19:19


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( yy, xx, J2 );

% Set up fittype and options.
ft = 'linearinterp';
opts = fitoptions( ft );
opts.Normalize = 'on';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'J2 vs. yy, xx', 'Location', 'NorthEast' );
% Label axes
xlabel( 'Pixeles' );
ylabel( 'Pixeles' );
zlabel( 'Intensidad' );
grid on
view( -47.5, 28 );


