function [fitresult, gof] = createFit(xx, cv)
%CREATEFIT(XX,CV)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xx
%      Y Output: cv
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Sep-2014 09:46:08


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xx, cv );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [0.00392156862745098 10 3.171287205266];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'cv vs. xx', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'xx' );
% ylabel( 'cv' );
% grid on


